pkg/alerts/nrql_alert_conditions.go, pkg/alerts/nrql_alert_conditions_integration_test.go, pkg/alerts/nrql_alert_conditions_test.go, pkg/alerts/nrql_alert_conditions_types.go
=> feat: add nqrl alert conditions

build/lint.mk, pkg/apm/apm.go, pkg/apm/apm_test.go, pkg/apm/deployments.go, pkg/apm/deployments_integration_test.go, pkg/apm/deployments_test.go, pkg/apm/deployments_types.go
=> feat: add deployments

pkg/apm/labels.go, pkg/apm/labels_integration_test.go, pkg/apm/labels_test.go, pkg/apm/labels_types.go
=> feat: add labels

internal/utils/utils.go, internal/utils/utils_test.go, pkg/apm/key_transactions.go, pkg/apm/key_transactions_integration_test.go, pkg/apm/key_transactions_test.go, pkg/apm/key_transactions_types.go
=> feat: add key transactions

pkg/plugins/components_test.go, pkg/plugins/plugins.go, pkg/plugins/plugins_integration_test.go, pkg/plugins/plugins_test.go, pkg/plugins/plugins_types.go
=> feat: add plugins

pkg/alerts/plugins_conditions.go, pkg/alerts/plugins_conditions_integration_test.go, pkg/alerts/plugins_conditions_test.go, pkg/alerts/plugins_conditions_types.go
=> feat: add plugins alert conditions

README.md, newrelic/newrelic.go
Update the readme with a usage example and add other packages to the main `newrelic` package.
=> docs: update readme example

pkg/alerts/alert_incidents.go, pkg/alerts/alert_incidents_test.go, pkg/alerts/alert_incidents_types.go
Resolves #73 
Adds ListAlertIncidents, AcknowledgeAlertIncident, and CloseAlertIncident functions to alerts package
=> Add support for Alerts Incident management

.circleci/config.yml
Enable Snyk scanning via CircleCI Orb
=> Add Snyk scanning

internal/http/client.go, internal/http/client_test.go, internal/region/region.go, internal/region/region_test.go, newrelic/newrelic.go, newrelic/newrelic_test.go, pkg/alerts/alerts.go, pkg/apm/apm.go, pkg/config/config.go, pkg/dashboards/dashboards.go, pkg/errors/errors.go, pkg/errors/errors_test.go, pkg/infrastructure/infrastructure.go, pkg/synthetics/synthetics.go, pkg/synthetics/synthetics_test.go
Looking at alternative ways to store config, and minimize the required imports for using the New Relic Client.
=> Refactoring Config

Makefile, build/test.mk, internal/testing/mock.go, internal/version/version_test.go, pkg/alerts/alerts_test.go, pkg/alerts/channels_test.go
It's not as clean as I'd like, but a starting point for refactoring the Mock setup for unit testing.
Also includes a test for the Version package to make sure we're keeping it consistent with the latest tagged release.
=> Added tests, and possible Mock refactor for discussion

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.3.0

README.md, internal/http/client.go, internal/http/graphql_client.go, internal/region/region.go, pkg/config/config.go, pkg/entities/entities.go, pkg/entities/entities_integration_test.go, pkg/entities/entities_types.go, pkg/entities/tags.go, pkg/entities/tags_integration_test.go, pkg/infrastructure/infrastructure.go
This PR introduces graphQL support and fills out entity and entity tag resource methods.
Resolves #66 and #67.
=> feat(entities): add entities search and entity tagging

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.4.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.5.0

pkg/alerts/synthetics_conditions.go, pkg/alerts/synthetics_conditions_integration_test.go, pkg/alerts/synthetics_conditions_test.go
This PR adds a `GetSyntheticsCondition` method to the alerts API.
=> feat(alerts): add GetSyntheticsCondition method

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.7.1

pkg/alerts/policy_channels.go, pkg/alerts/policy_channels_integration_test.go
=> fix(alerts): ensure multiple channels can be added via alert policy channel endpoint

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.8.0

pkg/alerts/channels.go, pkg/alerts/conditions.go, pkg/alerts/incidents.go, pkg/alerts/nrql_conditions.go, pkg/alerts/plugins_conditions.go, pkg/alerts/policies.go, pkg/alerts/synthetics_conditions.go, pkg/apm/applications.go, pkg/apm/deployments.go, pkg/apm/key_transactions.go, pkg/apm/labels.go, pkg/dashboards/dashboards.go, pkg/plugins/components.go, pkg/plugins/plugins.go
=> fix(http): Clear client responses between pages

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.9.0

pkg/synthetics/monitor_labels_integration_test.go
This PR fixes the flaky monitor label integration test.
=> tests(synthetics): fix flaky monitor labels integration test

pkg/synthetics/monitor_labels.go, pkg/synthetics/monitor_labels_test.go, pkg/synthetics/monitor_scripts.go, pkg/synthetics/monitors.go, pkg/synthetics/secure_credentials.go, pkg/synthetics/secure_credentials_integration_test.go, pkg/synthetics/secure_credentials_test.go, pkg/synthetics/synthetics.go, pkg/synthetics/synthetics_test.go, pkg/synthetics/synthetics_types.go
Resolves #134.
This PR adds a Synthetics secure credential resource to the client, following existing patterns.
=> feat(synthetics): add secure credentials resource

CHANGELOG.md, internal/version/version.go, pkg/synthetics/monitor_labels_integration_test.go
=> chore(changelog): Update CHANGELOG for v0.10.0

pkg/entities/entities.go, pkg/entities/entities_integration_test.go
=> fix(entities): tags filter needs to use type TagValue in graphql query

.chglog/config.yml, CHANGELOG.md, internal/version/version.go
BREAKING CHANGE for API key handling.
=> Release 0.12.0

CHANGELOG.md, internal/version/version.go
- **entities:** include applicationId for ApmApplicationEntity results
- **entities:** Make ApplicationID optional in results, omit if not returned by the API
- **http:** create a new errorValue for every request
- **apm:** refactor deployments resource to use new auth strategy
- **http:** refactor client to a request-scoped config context
=> Release 0.13.0

pkg/entities/entity.go
Facilitates **newrelic-cli** PR [#58](https://github.com/newrelic/newrelic-cli/pull/58)
=> chore(entities): add json tags for Entity struct fields

CHANGELOG.md, internal/version/version.go
- **newrelic:** add types for fields with well known values
=> Release v0.14.0

.circleci/config.yml, CHANGELOG.md, internal/version/version.go
- **build:** Force pull tags after each checkout
- update community support information
- **entities:** Add some more details from BrowserApplicationEntity
- **entities:** Return more data on ApmApplicationEntity, and be consistent in what we return between fetch and search
- **entities:** Change Entity.Type type... Add more to the ENUMs
=> chore(changelog): Update CHANGELOG for v0.16.0

pkg/alerts/alerts_test.go, pkg/alerts/policies.go, pkg/alerts/policies_integration_test.go
=> feat(alerts): implement graphql policy methods

pkg/alerts/channels.go, pkg/alerts/conditions.go, pkg/alerts/incidents.go, pkg/alerts/multi_location_synthetics_conditions.go, pkg/alerts/nrql_conditions.go, pkg/alerts/plugins_conditions.go, pkg/alerts/policy_channels.go, pkg/alerts/synthetics_conditions.go, pkg/apm/applications.go, pkg/apm/deployments.go, pkg/apm/key_transactions.go, pkg/apm/labels.go, pkg/dashboards/dashboard.go, pkg/plugins/plugins.go
=> docs(newrelic): use single-letter vars for receivers

pkg/entities/entities.go, pkg/nerdgraph/nerdgraph.go, pkg/workloads/workload.go, pkg/workloads/workload_integration_test.go, pkg/workloads/workloads.go
=> feat(workloads): add a workloads resource

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.17.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.17.1

newrelic/newrelic.go, pkg/workloads/workload.go
This PR fixes some bugs discovered when implementing a workloads resource in the NR Terraform provider.
=> fix(workloads): fix some bugs in the workloads implementation

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.18.0

internal/testing/helpers.go, pkg/alerts/conditions.go, pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
=> feat(alerts): add NerdGraph implementation for NRQL conditions

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.19.0

renovate.json
This PR adds a renovate config.
=> chore(newrelic): add renovate bot

internal/http/graphql.go, pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
Adjustments that were needed and discovered while implementing NerdGraph functionality in the Terraform Provider.
**Related**: `terraform-provider-newrelic` [PR #487](https://github.com/terraform-providers/terraform-provider-newrelic/pull/487)
=> fix(nrql_conditions): fix spelling errors and types

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.20.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.20.1

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.21.1

pkg/workloads/example_basic_test.go, pkg/workloads/workload.go, pkg/workloads/workload_integration_test.go
=> refactor(workloads): query with GUID per upstream API change

pkg/alerts/conditions.go, pkg/alerts/conditions_integration_test.go
relates to: https://github.com/terraform-providers/terraform-provider-newrelic/issues/506
=> fix(alerts): include "equal" operator for NRQL condition terms

pkg/dashboards/dashboard_integration_test.go, pkg/dashboards/dashboards_types.go
=> feat(dashboards): add grid_column_count field

.github/workflows/compile.yml, .github/workflows/test.yml
Looking to optimize the GH action workflows, testing out some splits
=> refactor(build): Split up github actions a bit

CHANGELOG.md, internal/version/version.go
Fix: Alerts resource paging issues (REST)
=> chore(changelog): Update CHANGELOG for v0.23.1

README.md
Update README to include the NR open source project header.
=> chore(docs): Add NR Open Source header

pkg/alerts/events.go, pkg/alerts/events_test.go
- Changing `ListAlertEventsParams` to the correct ones.
=> fix(alerts): Updating incorrect AlertEvents params

newrelic/newrelic.go, newrelic/newrelic_test.go
=> fix(region): gracefully fall back to default region

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.23.2

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.23.3

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.23.4

CHANGELOG.md, internal/version/version.go
- **edge:** add trace observer resource
=> chore(changelog): Update CHANGELOG for v0.24.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.25.0

CHANGELOG.md, internal/version/version.go
- **http:** Use default User-Agent header if none provided
- **http:** Refactor config.Compression and use it in http
- **http:** Enable compression handling for requests, consolidate POST methods
- **region:** Add Insights insert API URLs
=> chore(changelog): Update CHANGELOG for v0.26.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.27.0

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.27.1

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
Related: **terraform-provider-newrelic** [#607](https://github.com/terraform-providers/terraform-provider-newrelic/issues/607)
=> feat(alerts): implement NerdGraph methods for outlier NRQL alert conditions

CHANGELOG.md, internal/version/version.go
changelog for release **v0.28.0**
=> chore(changelog): Update CHANGELOG for v0.28.0

CHANGELOG.md, internal/version/version.go
Update CHANGELOG for **v0.28.1**
=> chore(changelog): Update CHANGELOG for v0.28.1

pkg/nrdb/nrdb.go, pkg/nrdb/nrdb_integration_test.go, pkg/nrdb/nrdb_query.go, pkg/nrdb/typegen.yaml, pkg/nrdb/types.go, pkg/nrdb/types_func.go
* Add ability to fetch NRQL query history.
* Expand what data is returned with a NRQL query
=> feat(nrdb): Fetch nrql query history

pkg/entities/entity.go, pkg/entities/entity_integration_test.go
As advertised on the tin.  Also backfills an acceptance test for Browser application entities.
=> feat(entities): surface underlying application IDs for mobile application entities

pkg/alerts/infrastructure_conditions.go, pkg/alerts/infrastructure_conditions_integration_test.go
=> feat(alerts): add description field to infra alert condition

.github/workflows/test.yml, pkg/alerts/infrastructure_conditions.go, pkg/alerts/infrastructure_conditions_integration_test.go, pkg/alerts/infrastructure_conditions_test.go
Related to [terraform-provider-newrelic #660](https://github.com/newrelic/terraform-provider-newrelic/issues/660)
=> fix(alerts): better handling of infra condition zero-value thresholds

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.33.2

pkg/events/events.go, pkg/events/events_batch.go
Fast follow for the previous PR because it's Friday and remembering to push is hard.
=> chore(events): Add some more nil checks / handling for batch mode

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.38.0

pkg/logs/example_log_batch_test.go, pkg/logs/example_log_test.go, pkg/logs/logs.go, pkg/logs/logs_batch.go
Implemented batch/queue mode for Log API
=> feat(logs): implement log batch mode

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.39.0

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
Facilitates: [newrelic/terraform-provider-newrelic #810](https://github.com/newrelic/terraform-provider-newrelic/issues/810)
=> feat(nrql_conditions): add new fields 'expiration' and 'signal'

internal/http/auth.go, pkg/alerts/alerts.go
This PR enables personal API key authentication for the Infrastructure Conditions API.
=> feat(alerts): enable personal api key auth for infra conditions

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.42.0

.github/workflows/compile.yml, README.md, go.mod
=> docs: update supported Go information and test config

internal/http/client_test.go, newrelic/doc.go, newrelic/example_basic_test.go, newrelic/newrelic.go, pkg/alerts/doc.go, pkg/apm/doc.go, pkg/config/config.go, pkg/config/doc.go, pkg/dashboards/doc.go, pkg/plugins/doc.go, pkg/synthetics/doc.go, pkg/synthetics/example_secure_credentials_test.go, pkg/synthetics/secure_credentials.go, pkg/synthetics/synthetics.go, pkg/testhelpers/config.go
This PR removes Admin API keys as an authentication mechanism.
=> feat: remove admin API key as an authentication mechanism

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
Add support for NRQL condition aggregationWindow (how frequently to bucket a NRQL condition query for evaluation)
This is a prerequisite for [#932](https://github.com/newrelic/terraform-provider-newrelic/pull/932) in the [New Relic Terraform Provider](https://github.com/newrelic/terraform-provider-newrelic)
=> feat(nrql alert condition)add signal.aggregation_window

go.sum, pkg/alerts/policies.go
=> fix(alerts): make error handling more resilient for alert policies

pkg/alerts/muting_rules.go
fixes: https://github.com/newrelic/terraform-provider-newrelic/issues/954
=> fix(muting_rules): ensure updates to disable rule are respected

pkg/entities/types.go
Update generated code using tutone
- make generate
- PR generated by [create-pull-request][1]
[1]: https://github.com/peter-evans/create-pull-request
=> chore(tutone): update generated code

.tutone.yml, pkg/entities/types.go
Knew this would come, and should of added them from the jump.
Add methods:
* GetAccountID
* GetDomain
* GetType
=> feat(entities): Add more methods to Entity(Outline)Interface

CHANGELOG.md, internal/version/version.go
=> chore(changelog): Update CHANGELOG for v0.55.2

Makefile, build/deps.mk, build/lint.mk, build/tools.mk, go.sum, pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api.go, pkg/dashboards/types.go, tools/go.mod, tools/go.sum
We are introducing a breaking change in the schema of the public dashboards API. It just involves updating the name of a couple of fields.
=> Update dashboards API

CHANGELOG.md, internal/version/version.go
Entities also updated for NRQLQueries on Dashboards
=> chore(changelog): Update CHANGELOG for v0.55.7

pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api_integration_test.go
Related to: [newrelic/terraform-provider-newrelic #1128](https://github.com/newrelic/terraform-provider-newrelic/issues/1128)
=> feat(dashboards): add linked entities to nr1 dashboard widgets

pkg/dashboards/dashboards_api.go, pkg/dashboards/types.go
Manually filtering out `queries` from GraphQL / structs until the schema is updated.
=> fix(dashboards): MANUAL CHANGE: remove queries until it is out of the schema

pkg/cloud/cloud_api.go, pkg/dashboards/dashboards_api.go, pkg/entities/entities_api.go, templates/nerdgraphclient/client.go.tmpl
- Change the template for query response structs as we've hit a schema that ends with Response.
=> refactor: Tutone auto-naming conflict with schema

CHANGELOG.md, internal/version/version.go
- **typegen:** do not attempt to unmarshal null data
- **nrqldroprules:** Implement NrqlDropRules
- Update all code-gen unmarshals with new typegen template
=> chore(changelog): Update CHANGELOG for v0.58.0

newrelic/newrelic.go
@jthurman42 looks like I forgot to actually return the Nrqldroprules client
=> fix(nrqldroprules): Actually return Nrqldroprules client

pkg/region/region_constants.go
=> fix(region_constants): corrected insightsBaseURL for EU

internal/serialization/epoch_time.go, internal/serialization/epoch_time_test.go
=> feat(serialization): Add Unix() command to EpochTime

.tutone.yml, go.sum, pkg/entities/types.go
=> feat(entity): Add EntityInterface.GetTags()

.tutone.yml, pkg/dashboards/dashboards_api.go, tools/go.mod, tools/go.sum
* Update Tutone to v0.7.0
* Fix manual override for Dashboards (GoldenMetrics/GoldenTags issue)
=> chore(build): Update Tutone

.tutone.yml, pkg/dashboards/types.go, pkg/nrtime/types.go
The tutone generate caught some new dashboard updates in #753 but recreated some time types.
=> chore(dashboards): Schema update

internal/http/graphql.go, pkg/alerts/nrql_conditions.go, pkg/alerts/policies.go
=> fix: retire usages of deprecated error schema

newrelic/newrelic.go
- Add missing bit to set up the API for service levels
=> fix(servicelevel): Initialize service level API with config

scripts/release.sh
Attempting to trigger a release via commit message.
=> fix: release test

pkg/dashboards/dashboards_widgets_integration_test.go, pkg/dashboards/type_overrides.go
Closes #836 with test cases.
Tests:
- Create without threshold
- Update to add threshold
- Update to remove all thresholds
=> fix(dashboards): make billboard widget thresholds optional

pkg/alerts/nrql_conditions_integration_test.go
https://newrelic.atlassian.net/browse/AINTER-8205
Corresponding TF Provider ticket https://github.com/newrelic/terraform-provider-newrelic/pull/1656
**This PR along with the corresponding TF Provider PR requires a MINOR release and should ensure the changelog has an entry noting the NRQL condition `ValueFunction` deprecation.**
This PR adds a test to create and update a static condition with and without a value function.  This work is to support the deprecation of the field `ValueFunction`.  See corresponding TF provider PR.
- I realized there weren't any code changes needed to support this deprecation, however, I decided to add a test.
- Originally, the goal was to remove `omitempty` from the update struct for `ValueFunction`; however, this was not possible because both static conditions …
=> chore(nrql_conditions): add test for optional value function for static nrql conditions

pkg/alerts/muting_rules.go, pkg/alerts/muting_rules_integration_test.go, pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go, pkg/alerts/nrql_conditions_test.go, pkg/alerts/policies_integration_test.go, pkg/synthetics/synthetics_api_integration_test.go
Fixes https://github.com/newrelic/terraform-provider-newrelic/issues/1430
=> fix(muting_rules): client not setting err.NotFound

.tutone.yml, pkg/notifications/destinations_test.go, pkg/notifications/notifications_integration_test.go, pkg/notifications/types.go
* Turn `AiNotificationsCredentialsInput` into pointer
=> fix(destinations): change credentials type to pointer

.tutone.yml, pkg/workloads/types.go, pkg/workloads/workloads_api.go
Updated workloads with missing fields
=> chore(deps): updated workloads

pkg/notifications/types.go
Add missing destination type via tutone tool
=> fix(notifications): add missing destination type via tutone

.tutone.yml, pkg/workloads/types.go
=> Workloads types

.tutone.yml, pkg/servicelevel/servicelevel_api.go, pkg/servicelevel/types.go
Updating service level model with latest changes to allow the usage of sum function.
=> feat: update servicelevel model

.tutone.yml, pkg/logconfigurations/logconfigurations_api.go, pkg/logconfigurations/obfuscation_rules_integration_test.go, pkg/logconfigurations/obfuscation_rules_test.go, pkg/logconfigurations/types.go
This PR includes:
* Obfuscation Rule - code generation and its tests
=> NR-62322: Added Obfuscation rule and tests

.tutone.yml, pkg/logconfigurations/data_partition_rule_integration_test.go, pkg/logconfigurations/logconfigurations_api.go, pkg/logconfigurations/types.go
=> NR-62316: Added Data partition and tests

pkg/changetracking/changetracking_api_integration_test.go, pkg/entities/tags_integration_test.go, pkg/workflows/types.go, pkg/workflows/workflows_api.go, pkg/workflows/workflows_integration_test.go, pkg/workflows/workflows_unit_test.go
This PR contains:
- Added field for workflows mutations and queries
- Generated code for new type
- Added tests for the new field
=> feat(Workflow): Add notification triggers

.tutone.yml, pkg/nrqldroprules/nrqldroprules_api.go, pkg/nrqldroprules/nrqldroprules_integration_test.go, pkg/nrqldroprules/types.go
🎫 - [NR-61328](https://issues.newrelic.com/browse/NR-61328)
This PR includes 
- NRQL drop rules - Errors
- Tests
=> NR-61328:NRQL drop rules errors 

pkg/changetracking/changetracking_api_integration_test.go, pkg/entities/tags_integration_test.go, pkg/workflows/types.go, pkg/workflows/workflows_api.go, pkg/workflows/workflows_integration_test.go, pkg/workflows/workflows_unit_test.go
Reverts newrelic/newrelic-client-go#961
=> Revert "Revert "feat(Workflow): Add notification triggers""

pkg/workflows/types.go, pkg/workflows/workflows_api.go, pkg/workflows/workflows_integration_test.go
Expose workflow entity GUID through the client
=> feat(workflows): expose workflow guid

pkg/logconfigurations/data_partition_rule_integration_test.go, pkg/logconfigurations/logconfigurations_api.go, pkg/logconfigurations/types.go
Modified the data partitions by replacing matchingCriteria with nrql.
[NR-72647](https://issues.newrelic.com/browse/NR-72647)
=> chore(data_partition): new attribute nrql and updated tests ; NR-72647

pkg/logconfigurations/parsing_rule_integration_test.go
Refactoring the data partitions tests
=> chore(parsing_rules): tests refactor

pkg/servicelevel/service_level_integration_test.go, pkg/servicelevel/servicelevel_api.go, pkg/servicelevel/types.go
Changes include support to configure SLIs using the GET_FIELD and GET_CDF_COUNT functions. Additionally, it has been introduced a new threshold property that is necessary for CDF.
=> feat: Update servicelevel schema

pkg/dashboards/dashboards_types.go
Please check [PR #2326](https://github.com/newrelic/terraform-provider-newrelic/pull/2326) in the Terraform Provider for an elaborate description on the need of this PR.
=> fix(dashboard): altering the 'Min' field in DashboardWidgetYAxisLeft

pkg/entities/entities_api.go, pkg/entities/entity_integration_test.go, pkg/entities/types.go
[SDK] Add method to support the key transaction entities in client go
=> feat(entity): Add method to support the key transaction entities in client go.

pkg/logconfigurations/types.go
fix issue with enable attribute
=> fix(data_partition): fix issue with enable attribute

pkg/synthetics/synthetics_api_integration_test.go, pkg/usermanagement/groups_integration_test.go, pkg/usermanagement/groups_unit_test.go, pkg/usermanagement/usermanagement_api_queries.go, pkg/usermanagement/usermanagement_test.go
=> fix(group_management): alter group management queries and add tests

pkg/events/events_batch.go, pkg/logs/logs_batch.go
Amends the commit message to allow for releases.
=> fix: Logger string interpolation (#1104)

.tutone.yml, pkg/changetracking/changetracking_api_integration_test.go, pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api.go, pkg/dashboards/dashboards_api_integration_test.go, pkg/dashboards/types.go, pkg/entities/entity_integration_test.go, pkg/entities/tags_integration_test.go, pkg/entities/types.go, pkg/nerdstorage/nerdstorage_integration_test.go, pkg/servicelevel/service_level_integration_test.go, pkg/testhelpers/helpers.go
JIRA: https://new-relic.atlassian.net/browse/NR-170831
=> feat(dashboards): Added ignore time picker as options field to the dashboard variables

.tutone.yml, pkg/entities/types.go
Fixes the following fatal error:
Types were generated but manually added this particular entity type to ensure continued compatibility.
=> feat(entities): add KeyTransactionEntity types 

.github/workflows/codeql.yml, .github/workflows/test.yml
=> chore(deps): update some more deps

.tutone.yml, pkg/entities/entities_api.go, pkg/entities/entity_integration_test.go, pkg/entities/types.go
Generated entity query with max depth of 4. This will override the manually added changes to fix drift as part of this PR: https://github.com/newrelic/newrelic-client-go/pull/1186
=> fix(entity): regenerated 'entity' query max depth of 4

README.md
=> feat: minor change in README.md test commit

.goreleaser.yml
=> fix(goreleaser): try replacing build with builds for v2 config

pkg/installevents/installevents_api.go, pkg/installevents/types.go
JIRA: https://new-relic.atlassian.net/browse/NR-333919
These changes include adding a new field called optimized message to the existing install status events
=> feat: Add optimized error message to the recipe event

pkg/entities/types.go, pkg/workflows/types.go
Description
Jira Ticket: NR-348444.
Added Investigate trigger state, which performs similar function as acknowledge state.
Testing
Unit or Integration testing is not required for this change as no explicit tests are written for other triggers
=> feat(workflows): adds new `notification_trigger` type `INVESTIGATING`

scripts/release.sh
updated release script to populate release notes
=> fix(release): updated release script to populate release notes

scripts/release.sh
updated missing depenedencies in release script
=> fix(release): updated missing depenedencies in release script

.github/workflows/test.yml
=> fix(build): added codecov token to be used from secrets for reporting code coverage

README.md
fix(docs): mock release for a test inclusive of a README update
=> fix(docs): mock release for a test inclusive of a README update

newrelic/newrelic.go, pkg/users/users.go
for https://github.com/newrelic/terraform-provider-newrelic/pull/2884
=> fix: fixes users pkg

pkg/cloud/cloud_api.go, pkg/cloud/types.go
Adding Support for new integration : Aws SecurityHub to cloud.
Raising this PR as a part of enabling the integration of AWS Security Hub via Terraform.
Jira ticket : https://new-relic.atlassian.net/browse/NR-412555
=> feat(security-rx) Add support for Aws SecurityHub integration

pkg/agentapplications/agentapplications_integration_test.go, pkg/agentapplications/types.go
GSTE: https://new-relic.atlassian.net/browse/NR-421126
- Fixed a bug in the APM application browser package where distributed tracing's boolean was misfunctioning.
=> fix: fixed a distributed tracing bug in the browser package

.tutone.yml, go.mod, go.sum, internal/http/client.go, pkg/changetracking/changetracking_api.go, pkg/changetracking/changetracking_api_integration_test.go, pkg/changetracking/customattributes.go, pkg/changetracking/customattributes_test.go, pkg/changetracking/types.go, pkg/entityrelationship/entityrelationship_api.go, pkg/logs/example_log_test.go
This PR includes the latest change tracking api, refer [doc](https://docs.newrelic.com/docs/change-tracking/change-tracking-events/#simple-mutation). 
This also fixes the issues with the custom types and the logs package tests failure
=> feat(change-tracking): included change tracking api

pkg/dashboards/dashboards_types.go
This PR aims to add tooltip support in dashboard rawConfiguration.
=> feat(tooltip-support): add tooltip support in dashboard rawConfiguration

pkg/cloud/cloud_api.go, pkg/cloud/cloud_api_integration_test.go, pkg/cloud/types.go
Add support for OCI linkAccount and updateAccount and configurations
JIRA LINK: https://new-relic.atlassian.net/browse/NR-437888
TERRAFORM PR: https://github.com/newrelic/terraform-provider-newrelic/pull/2936
Test:
=> feat(oci): add support for OCI linkAccount and configurations

pkg/dashboards/dashboards_types.go
This PR aims to add support for billboard settings in dashboards.
=> fix(billboard-settings): add support for billboard settings in dashboards
