.gitignore, Makefile, README.md, build/compile.mk, build/lint.mk, build/test.mk, go.mod, go.sum, newrelic/newrelic.go, pkg/alerts/alert_policies_test.go, pkg/alerts/alert_policy_channels_test.go, pkg/alerts/alert_policy_channels_types.go, pkg/apm/applications_test.go, pkg/dashboards/dashboards_test.go, pkg/synthetics/monitor_scripts_integration_test.go, tools.go
For some reason, golangci-lint has stopped working as expected.  I've updated the make system to directly call a handful of linters instead.
- misspell: Spell check all files (not just source code)
- gofmt: File formatting
- go vet
- golint
- ineffassign: ineffectual assignments
- gocyclo: cyclomatic complexities of functions
- deadcode: Unused code
- bodyclose: HTTP response bodies are closed correctly
Also fixed the linting issues found with the above checks.
=> Linter updates

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, pkg/errors/errors.go
Resolves #69.
This PR exposes the error types for the client so they can be used in the calling code.  A common use case for this is checking if the error is due to a resource not found error.
=> feat: publicly expose error types

pkg/alerts/infrastructure_conditions_test.go, pkg/alerts/infrastructure_conditions_types.go
The API endpoint accepts a float for Infrastructure Alert Condition value, update the client to use float.
* Change field from `int` to `float64`
* Add test for Warning threshold
* Test using float and int in JSON response body
=> bug: Change Infra alert condition value to float

pkg/synthetics/monitor_scripts.go, pkg/synthetics/monitor_scripts_integration_test.go, pkg/synthetics/monitor_scripts_test.go
This PR updates the UpdateMonitorScript method to do the necessary base64 encoding and decoding for the script text so it isn't necessary for the end user.
=> feat: encode monitor script text

internal/http/client.go, internal/http/client_test.go, pkg/alerts/alerts.go, pkg/apm/apm.go, pkg/config/config.go, pkg/dashboards/dashboards.go, pkg/synthetics/synthetics.go
This PR pulls the various API URLs public so they can be referenced by users of the various packages.
=> chore: expose region urls

.circleci/config.yml
Snyk should run, but not cause failures on PRs for now.
=> Disable snyk issues to fail the build on CircleCI

internal/http/client.go, internal/http/client_test.go, pkg/alerts/channels.go, pkg/alerts/conditions.go, pkg/alerts/nrql_conditions.go, pkg/alerts/plugins_conditions.go, pkg/alerts/policies.go, pkg/apm/labels.go, pkg/errors/errors.go, pkg/errors/errors_test.go
The `ErrorNotFound` type is meaningful for downstream use in the Terraform provider.  It initially represented a 404 response from a REST Show endpoint, but it should also be used for Get methods that do not have corresponding Show endpoints and need to iterate over results returned from a List endpoint .
This PR puts the ErrorNotFound type in place for these scenarios, and also allows for custom error messages.
=> fix: make use of ErrorNotFound type for Get methods that are based on List methods

pkg/alerts/alerts_test.go, pkg/alerts/channels_test.go, pkg/alerts/incidents_test.go, pkg/alerts/policies_test.go, pkg/apm/apm_test.go, pkg/apm/applications_test.go, pkg/apm/key_transactions_test.go, pkg/dashboards/dashboards_test.go, pkg/plugins/components_test.go, pkg/plugins/plugins_test.go, pkg/synthetics/synthetics_test.go
Resolves: #34 
This PR also includes some minor refactor for a few unit tests to use our latest patterns.
=> refactor: update test helpers to use new mock server

internal/http/retry.go
This PR introduces up to 3 HTTP request retries if the server sends back a 429 (Too Many Requests) as the response's status code.   This counteracts the aggressive rate limiting policy of the Synthetics API (6 req/sec), which often leads to integration test failures.
=> fix: retry HTTP requests on 429 status codes

README.md, newrelic/newrelic.go, newrelic/newrelic_test.go
This PR exposes the `Entities` API via the `newrelic` catchall client, and abstracts the api key configuration behind `ConfigOption` methods.
=> refactor: validate that at least one API key is provided

build/test.mk, internal/version/version_test.go, pkg/dashboards/dashboards_integration_test.go, pkg/plugins/components_integration_test.go, pkg/plugins/components_test.go, pkg/synthetics/monitors_integration_test.go
We need to skip `TestVersionTag` on releases because it will inevitably fail due to version mismatches on those PRs
=> chore(internal/version): skip version test on release branches

pkg/alerts/alerts_types.go, pkg/alerts/channels_integration_test.go, pkg/alerts/channels_test.go
Resolves: #101 
The New Relic v2 API endpoint for alert channels returns two different data types for `configuration.payload` and `configuration.headers`. If either of those fields is "empty" or left black when creating an alert channel in the UI, the API will return an empty string. But if headers and/or payload are included in an alert channel, the API will return an object, hence the need for a custom umarshal method for those fields.
**Example responses:**
Population headers and payload
```
{
"type": "webhook",
"configuration": {
"headers": {                            
"x-header-test": "header-value"  <-- notice we have an object here
},                                                 
"payload": {                                 
"account_id": "$ACCOUNT_ID"   <-- notice we have an …
```
=> fix(alerts): custom unmarshal of channel configuration Headers and Payload fields

CHANGELOG.md, internal/version/version.go
Releasing v0.6.0.
I pushed up the tag ahead of time, if this works better I'll update the release runbook to match.
=> chore(changelog): Update CHANGELOG for v0.6.0

internal/http/graphql_client.go, newrelic/newrelic.go, newrelic/newrelic_test.go, pkg/alerts/alerts.go, pkg/alerts/alerts_test.go, pkg/config/config.go, pkg/entities/entities_test.go, pkg/synthetics/synthetics.go, pkg/synthetics/synthetics_test.go
This PR adds the ability to configure base URLs per API when using the rollup client in the `newrelic` package.
=> feat(newrelic): add the ability to configure base URLs per API

internal/http/client.go, internal/http/client_test.go, internal/logging/structured_logger.go, newrelic/newrelic.go, newrelic/newrelic_test.go, pkg/config/config.go, pkg/entities/entities.go, pkg/entities/entities_integration_test.go
This PR updates a few things for conventions' and cleanliness' sake:
- Remove some unnecessary `fmt.Printf`s in test code
- Remove pointers to the `RoundTripper` interface when passing an HTTP transport via config
- Renames `ListEntitiesParams` to `SearchEntitiesParams` for consistency
=> refactor: post-release clean up

pkg/alerts/alerts_types.go, pkg/alerts/channels_integration_test.go, pkg/alerts/channels_test.go
Fixes: #101 
An alert channel `payload` can be more complex than `{ "key": "value"}`, such as having nested objects or arrays. We need to update the types to fix serialization. Also of note, the NR v2 API allows complex nesting for `headers` as well, so we also need to handle this scenario.
=> fix(alerts): handle more complex JSON structures in payload or headers

pkg/alerts/channels_integration_test.go, pkg/apm/apm_types.go, pkg/apm/applications.go, pkg/apm/applications_integration_test.go, pkg/apm/applications_test.go
resolves: #79
Currently there is no facility in the code to query for the application metric
names or data.  Here we take a first pass implementation for the /metrics.json
and /metrics/data.json endpoints of the APM API.
=> feat(apm): Add support application metric names and data

pkg/alerts/alerts_types.go, pkg/alerts/channels_test.go
This PR fixes unmarshaling of alert channel webhook headers and payload when the API returns string representations of JSON objects, like so:
```json
"configuration": {
"headers": "{\"key\":\"value\"}",
"payload": "{\"key\":\"value\"}",
},
```
=> fix: allow string representations of JSON for alert channel webhook and payload

pkg/alerts/alerts_types.go, pkg/alerts/multi_location_synthetics_conditions.go, pkg/alerts/multi_location_synthetics_conditions_integration_test.go, pkg/alerts/multi_location_synthetics_conditions_test.go
resolves: #72
Currently there is no facility to manage location_failure_conditions in the
Alerts API.  Here we add what is necessary to manage these resources.
=> feat(alerts): Implement multi-location synthetics conditions

internal/http/client.go, internal/logging/logger.go, internal/logging/structured_logger.go, newrelic/newrelic_test.go
This PR introduces trace level logging for lower level request information such as request and response body and headers.  It disables the default debug-level request logging of go-retryablehttp and moves it instead into the client's `do` method.
Related to terraform-providers/terraform-provider-newrelic#377.
=> feat(http): add trace logging with additional request info

internal/http/client.go, pkg/synthetics/monitor_labels.go, pkg/synthetics/monitor_labels_integration_test.go, pkg/synthetics/monitor_labels_test.go, pkg/synthetics/synthetics.go, pkg/synthetics/synthetics_test.go, pkg/synthetics/synthetics_types.go
resolves: #129
This change bumps the version of the synthetics API in use to support the label
management that is included in this change.
=> feat(synthetics): implement label monitor support

Makefile, build/release.mk, tools/release.sh
This PR introduces a new `make release` target to facilitate the release process. The [runbook](https://source.datanerd.us/developer-toolkit/runbooks/wiki/New-Relic-Go-SDK) has also been updated.
Example `make` command:
- `make release version=0.11.0`
=> feat(ci): the beginnings of some release automation

internal/http/client.go, internal/http/client_test.go, internal/http/test_helpers.go, pkg/config/config.go
This PR adds some additional test coverage to the internal http client implementation including:
* RawPost type detection (to prevent panic)
* RawPost unit tests
* additional header tests (all set headers)
* Allows consuming app to set the service name header
=> chore(tests): improve http client tests

newrelic/newrelic.go, newrelic/newrelic_test.go
Added ServiceName config option, but did not allow it to be set.  This adds a ConfigOption to set ServiceName so it can be used in the future for logging.
=> fix(newrelic): Add option to set ServiceName in Config

.github/stale.yml, .gitignore
This PR configures the [Stale](https://probot.github.io/apps/stale/) GItHub app for this repo. This GH app facilitates automatically closing stale issues and pull requests (we're only configuring this for issues for now).
=> chore: add stale bot config for auto-management of stale issues

internal/http/auth.go, internal/http/client.go, internal/http/client_test.go, internal/http/graphql_client.go, pkg/alerts/alerts.go, pkg/alerts/alerts_test.go, pkg/apm/apm.go, pkg/apm/apm_test.go, pkg/plugins/plugins_test.go
This PR allows Personal API keys to be used for authentication in the V2 endpoints that allow it (currently only the resources defined in the `apm` and `alerts` packages).
Compatibility mode will be enabled if a personal API key has been provided and the mode has been enabled within the package instantiating the client.
=> feat(http): allow personal API keys to be used for alerts and APM resources

CHANGELOG.md, internal/version/version.go
Releasing 0.11.0.
This PR allows the use of personal API keys for APM and alerts resources.
=> chore(changelog): Update CHANGELOG for v0.11.0

newrelic/newrelic.go, pkg/nerdgraph/nerdgraph.go, pkg/nerdgraph/nerdgraph_integration_test.go
Resolves: #149 
First pass at adding the ability to pass raw GraphQL queries directly via a client method. 
This facilitates being able to execute a CLI command that passes a raw GraphQL query to the client.
```
newrelic graphql query "{ actor { user { email id name } } }"
```
```
newrelic graphql query 'query($guid: EntityGuid!) { actor { entity(guid: $guid) { guid name domain entityType } } }' --variables '{"guid": "MjUyMDUyOHxBUE18QVBQTElDQVRJT058MjE1MDM3Nzk1"}'
```
=> feat(nerdgraph): implement ability to make raw GraphQL query

README.md, internal/http/auth.go, internal/http/client.go, internal/http/client_test.go, internal/http/test_helpers.go, newrelic/newrelic.go, newrelic/newrelic_test.go, pkg/alerts/alerts_test.go, pkg/alerts/synthetics_conditions_integration_test.go, pkg/apm/apm_test.go, pkg/config/config.go, pkg/dashboards/dashboard_integration_test.go, pkg/dashboards/dashboards_test.go, pkg/entities/entity.go, pkg/entities/entity_integration_test.go, pkg/nerdgraph/nerdgraph_integration_test.go, pkg/plugins/components_integration_test.go, pkg/plugins/plugins_test.go, pkg/synthetics/monitor_labels_integration_test.go, pkg/synthetics/monitor_scripts_integration_test.go, pkg/synthetics/monitors_integration_test.go, pkg/synthetics/secure_credentials_integration_test.go, pkg/synthetics/synthetics_test.go
Align API key names with our public docs.
This breaks:
* `ConfigAPIKey` as it becomes `ConfigAdminAPIKey`
* `NEWRELIC_PERSONAL_API_KEY` becomes `NEW_RELIC_API_KEY` <= Personal API Key
* `NEWRELIC_API_KEY` becomes `NEW_RELIC_ADMIN_API_KEY` <= Admin API Key
=> BREAKING CHANGE: Change API Key field names

pkg/entities/entity.go
Current behavior is to return the zero value for `int` instead of leaving the field off.  This changes the behavior, omit the field if it's nil.
=> Omit ApplicationID if not returned

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, internal/http/graphql_client.go, pkg/infrastructure/infrastructure.go, pkg/synthetics/synthetics.go
Resolves #161.
This PR ensures that the `errrorValue` instance is not shared among multiple requests, eliminating shared state for concurrent requests.
=> fix(http): create a new errorValue for every request

pkg/nerdgraph/nerdgraph.go
This facilitates encoding the query result in the CLI (newrelic-cli PR [#58](https://github.com/newrelic/newrelic-cli/pull/58)), which is will be returning a raw string to ensure integers are parsed correctly.
=> chore(nerdgraph): export nerdgraph query response struct

internal/http/auth.go, internal/http/client.go, internal/http/request.go, pkg/apm/apm.go, pkg/apm/deployments.go
Resolves #156 .
This PR refactors the client to a request-scoped API and removes personal key auth for APM resources aside from deployments.
=> refactor(http): configurable requests

pkg/alerts/channels.go, pkg/alerts/channels_integration_test.go, pkg/alerts/channels_test.go, pkg/alerts/conditions.go, pkg/alerts/conditions_integration_test.go, pkg/alerts/conditions_test.go, pkg/alerts/policies.go, pkg/alerts/policies_integration_test.go, pkg/alerts/policies_test.go
Resolves #130 .
This PR adds enum-style, `string`-backed types for resource fields that have well-known values.
=> feat(newrelic): add types for fields with well known values

pkg/alerts/conditions.go, pkg/alerts/conditions_integration_test.go, pkg/alerts/conditions_test.go, pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go, pkg/alerts/nrql_conditions_test.go, pkg/alerts/plugins_conditions.go, pkg/alerts/plugins_conditions_integration_test.go, pkg/alerts/plugins_conditions_test.go
Resolves: #120 
Downstream changes will need to be made in [terraform-providers/terraform-provider-newrelic](https://github.com/terraform-providers/terraform-provider-newrelic).
=> refactor: remove transient PolicyID on conditions structs for 1:1 mapping to API responses

pkg/alerts/incidents.go, pkg/alerts/incidents_test.go
Resolves #121 . 
This PR makes use of the `serialization.EpochTime` type for incident timestamp fields, for consistency with other resources.
=> refactor(alerts): use consistent types for incident timestamp fields

internal/http/client.go, internal/http/client_test.go, internal/http/request.go
Resolves #175 .
This PR fixes overriding of the service name header.
=> fix(http): allow overriding of service name

.circleci/config.yml
On release merge to master, `checkout` in CircleCI appears not to update a cache as expected, and the tags are not pulled in.  This should force the tags to be fetch after checkout every new run
=> fix(build): Force pull tags after each checkout

pkg/entities/entity.go, pkg/entities/entity_integration_test.go
* Change the way we generate the GraphQL queries to be composable, and consistent between fetching (GetEntity/GetEntities, and Entity Search)
* Increase the amount of data Entity returns for `ApmApplicationEntity`.
* Add Integration tests for returning additional fields
* Add Integration tests for base Entity fields
* Add a few more fields for `BrowserApplicationEntity`
This does change the type of `entities.Entity.Type` from `string` to `EntityType` which is a breaking change.
=> Expand data returned by `entity`, make search/fetch consistent

pkg/workloads/workload.go, pkg/workloads/workload_integration_test.go
This PR updates the underlying type for `EntitySearchQuery.CreatedAt` in response to a recent change to the underlying API.
=> fix(workloads): use epoch time for EntitySearchQuery.CreatedAt

pkg/alerts/conditions_test.go, pkg/alerts/serialization.go
This PR introduces custom unmarshaling for the `ConditionTerm` struct to allow for unmarshaling of a broader set of values.
=> fix(alerts) add custom unmarshaling for ConditionTerm

pkg/workloads/example_basic_test.go, pkg/workloads/workload.go, pkg/workloads/workload_integration_test.go
This PR removes the unnecessary use of nullable struct fields for structs that map to NerdGraph types.
=> fix(workloads): remove nullable struct fields unless necessary

.goreleaser.yml, go.mod, go.sum
Update goreleaser, and update config so our library release hack isn't needed and the full release process should succeed (was failing with empty checksum file)
=> Fix: goreleaser now with real library support

internal/testing/config.go, newrelic/newrelic.go, pkg/config/config.go, pkg/region/errors.go, pkg/region/errors_test.go, pkg/region/region.go, pkg/region/region_constants.go, pkg/region/region_test.go
Previous behavior for `region.Parse(<string>)` was to return the entire region.  Since we have a use-case for validating only the String => region.Name
New behavior:
* `region.Default` is a Name (not the entire Region struct) and a constant
* `region.Parse(string)` returns the `region.Name` or an error
* `region.Get(Name)` returns a copy of the region from the map of valid regions (DRY of copy due to non-constant structs)
=> Split parsing / fetching of region data

pkg/workloads/example_basic_test.go, pkg/workloads/workload.go, pkg/workloads/workload_integration_test.go
This PR removes some deprecated fields from the Workloads resource and re-enables a previous failing test.
cc @bthemad
=> refactor(workloads): remove deprecated fields

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, internal/http/graphql.go, pkg/alerts/policies.go, pkg/infrastructure/infrastructure.go, pkg/synthetics/synthetics.go
This PR returns a NotFound error when a policy can't be located in NerdGraph.
=> fix(alerts): return a NotFound error when policies are not found in NerdGraph

pkg/alerts/multi_location_synthetics_conditions_integration_test.go
The API endpoint `PUT /v2/alerts_location_failure_conditions/{id}.json` is currently broken, hence disabling the integration test temporarily.
=> tests(alerts): temporarily disable test case for UpdateMultiLocationSyntheticsCondition

pkg/dashboards/dashboard_integration_test.go, pkg/dashboards/dashboards_types.go
This `GridColumnCountTypes` enum provides better specificity for column support per product/platform
=> chore(dashboards): add enum for grid column count

.goreleaser.yml, build/document.mk, build/release.mk
Backport change log for the Releases page from other tooling, and a bit of cleanup to get it all working.
=> chore(build): Cleanup release process to include GH changelog generation

CHANGELOG.md, internal/version/version.go
- **build:** Github actions `make lint` for commit messages need full history
- **workloads:** Removing deprecated field `name` from `entitySearchQuery`
- **typegen:** Add a README for typegen
- **events:** add alert events
- **build:** Split up github actions a bit
- **typegen:** Split/refactor much of typegen internals
=> Release v0.23.0

pkg/alerts/channels.go, pkg/alerts/conditions.go, pkg/alerts/incidents.go, pkg/alerts/multi_location_synthetics_conditions.go, pkg/alerts/nrql_conditions.go, pkg/alerts/plugins_conditions.go, pkg/alerts/synthetics_conditions.go
Paging for many, but not all, of the alert data fetches were broken with region update in 0.20.0.
Linked issues:
* https://github.com/terraform-providers/terraform-provider-newrelic/issues/544
* https://github.com/terraform-providers/terraform-provider-newrelic/issues/545
* https://github.com/terraform-providers/terraform-provider-newrelic/issues/547
=> fix(alerts): Alerts paging was incorrectly generating URLs

pkg/workloads/workload.go
This PR fixes a broken workloads query, probably introduced due to upstream API validation changes.
=> fix(workloads): fix query type for entity guid

pkg/alerts/conditions.go
Related to terraform-providers/terraform-provider-newrelic#563.
This PR allows a blank Runbook URL to be sent.  The underlying API does not remove a runbook URL on update if the passed payload omits the `runbook_url` attribute, so we will need to explicitly pass a blank string.
=> fix(alerts): allow blank runbook URL to be sent

pkg/apm/applications_integration_test.go, pkg/apm/applications_metrics.go
Resolves: #292
**TL;DR**
Current params struct for MetricsDataParams
```go
type MetricDataParams struct {
Names     []string   `url:"names,omitempty"`
Values    []string   `url:"values,omitempty"`
// ...
}
```
Should be the following: (notice the `[]` addition to the json tags)
```go
type MetricDataParams struct {
Names     []string   `url:"names[],omitempty"`
Values    []string   `url:"values[],omitempty"`
// ...
}
```
=> fix(apm): adjust MetricDataParams json tags to support lists in query params

CHANGELOG.md, internal/version/version.go
- **apm:** don't return empty zero values for floats for MetricTimesliceValues which can be misleading
- **apm:** adjust MetricDataParams json tags to support query params as arrays
=> chore(changelog): Update CHANGELOG for v0.24.1

internal/http/auth.go, internal/http/client.go, internal/http/client_test.go, internal/http/compress.go, internal/http/compress_test.go, internal/http/request.go, pkg/config/compression.go, pkg/config/config.go, pkg/region/region.go, pkg/region/region_constants.go, pkg/synthetics/monitor_labels.go
This PR accomplishes two goals:
* Add Insights URLs / building to Region
* Implement compression (none and gzip) in the http client, so sending data is optimized
The compression is not directly inline by default, however there is on spicy refactor: Removal of RawPost, and collapsing that logic into the [request](https://github.com/newrelic/newrelic-client-go/pull/322/files#diff-c8120cadd719e78b5424e31344a1b4e0R51).  In this case, anything that is already a `[]byte` is not marshaled to JSON, anything else is.  The one RawPost use-case has been updated (wrap: `[]byte("string:notJSON")`)
=> HTTP Compression / Prep for Insights

internal/http/request.go, pkg/config/config.go
This addresses the issue of incomplete user-agent headers by default:
* Calls to `config.New()` set the user-agent incorrectly (does not include full user-agent info like version)
* Add check to NewRequest to ensure that either the user-agent specified of the default is added to all requests.
=> Use default User-Agent header if none provided

internal/serialization/epoch_time.go, internal/serialization/epoch_time_test.go, pkg/alerts/infrastructure_conditions_test.go, pkg/alerts/policies_test.go
We currently do not correctly handle unmarshalling of Unix timestamps that have millisecond resolution, and instead count them as additional seconds projecting the timestamp out 50k years into the future.
Resolves #328
=> [fix]: EpochTime Serialization with Milliseconds

pkg/alerts/nrql_conditions.go
This PR adds a proxy method for deleting NRQL alert conditions via NerdGraph, which also facilitates resource API consistency.
=> feat(alerts): add DeleteNrqlConditionMutation as a proxy to DeleteConditionMutation

internal/serialization/epoch_time.go, internal/serialization/epoch_time_test.go, pkg/alerts/policies_test.go, pkg/nrdb/types_func.go
The current serialization.EpochTime does not set the location to anything, making testing difficult and making assumptions on the time zone.
* On (un)marshalJSON, set timezone to UTC
* Fix unmarshal of Nanosecond resolution times (found while adding tests for String())
* Add String() to print out the time in a human readable format
* Add String() to nrdb.EpochSeconds and nrdb.EpochMilliseconds (lower level type is serialization.EpochTime)
=> fix(serialization): set location to UTC, fix nanosecond handling

CHANGELOG.md, internal/version/version.go
- **nrdb:** Add String() to Epoch* types
- **serialization:** set tz UTC on MarshalJSON
- **serialization:** Fix nanosecond handling, set tz UTC, add EpochTime.String()
=> chore(changelog): Update CHANGELOG for v0.30.2

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go, pkg/synthetics/monitor_labels_integration_test.go
Resolves: #385
---
This PR also removes some extraneous test cases that are no longer relevant for monitor labels. Integration tests were failing for `TestIntegrationGetMonitorLabels` due to the following error. Tags are the future-facing resource. Labels are being removed and considered legacy.
> Error 403 Tag migration has already occurred for this account. Adding and removing labels is not allowed.
=> fix(nrql_conditions): better zero-value marshalling for threshold

pkg/alerts/infrastructure_conditions.go, pkg/alerts/infrastructure_conditions_integration_test.go
The infra API needs description explicitly set in the JSON to an empty string for updating/deleting it.
=> fix(alerts): always send infra condition description even if its an empty string

internal/http/graphql.go
Surface Nerdgraph validation errors in the graphQL error messages.  This will change error messages like this:
```
Error: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"Validation Error"}]
```
to messages like this:
```
Error: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT","validationErrors":[{"name":"name","reason":"length must be between 0 and 64"}]},"message":"Validation Error"}]
```
=> feat(graphql): capture validation error output from API response

pkg/events/events.go, pkg/events/events_batch.go, pkg/events/events_integration_test.go, pkg/events/example_batch_test.go
Add ability to start a background queue of events, and batch post them to New Relic.
Porting from newrelic/go-insights with some updates / modifications.
Closes #310
=> feat(events): Batch event insertion

newrelic/newrelic.go, newrelic/newrelic_test.go
We currently require either a Personal or Admin API key, each unlocking a specific set of actions.  This enables a pure Insert mode (just the Insights Insert Key required), so the `newrelic.Events.BatchMode` can be leveraged without having to build-out the sub-package itself.
=> Allow just an insert key for the newrelic package

CHANGELOG.md, internal/version/version.go
- **newrelic:** Allow just an insert key for the newrelic package
=> chore(changelog): Update CHANGELOG for v0.35.1

.gitignore, newrelic/newrelic.go, pkg/apiaccesskeys/apiaccesskey.go, pkg/apiaccesskeys/apiaccesskeys.go, pkg/apiaccesskeys/types.go
Resolves https://github.com/davidji99/newrelic-client-go/issues/2
This is a WIP to eventually address https://github.com/newrelic/terraform-provider-newrelic/issues/839.
Personally, I'm a bit confused how this client API prefers to implement the NerdGraph APIs.
=> Implement new endpoints for managing license keys

pkg/entities/entity.go, pkg/entities/tags.go
related to https://github.com/newrelic/terraform-provider-newrelic/issues/756, https://github.com/newrelic/terraform-provider-newrelic/issues/791 and https://github.com/newrelic/terraform-provider-newrelic/issues/766
The nerdgraph schema has been updated to include the information about a users chances of modifying a given entity tag.  Here we hide those which are not user-editable from the user.
=> Implement TagsWithMetadata to avoid non-modifiable result sets

internal/http/auth.go, pkg/logs/logs.go
Added ability to use an insert key to send logs. Only a license key was supported previously.
=> feat(logs): support insert key

internal/http/graphql.go, pkg/alerts/nrql_conditions_integration_test.go
Facilitates resolving: [terraform-provider-newrelic #860](https://github.com/newrelic/terraform-provider-newrelic/issues/860)
The issue above might have been caused by an upstream API change 🤔 💭
=> fix(http): handle 'not found' downstream response

internal/http/graphql.go, pkg/alerts/nrql_conditions.go
Refactors #475 
The previous change was a widespread change and currently it's safer to scope this change to the resource in question rather than for all of them.
=> refactor(alerts): remove widespread change, limit scope to only nrql condition error resp handling

pkg/events/events.go
Without the change, the received data type is a pointer and never posted to
insights.  Here we dereference the pointer so the data flows properly.
=> fix(events): dereference the data pointer

pkg/alerts/example_policy_test.go, pkg/apm/example_application_test.go, pkg/apm/example_key_transaction_test.go, pkg/apm/example_labels_test.go, pkg/dashboards/dashboards.go, pkg/dashboards/example_dashboard_test.go, pkg/synthetics/example_monitor_test.go, pkg/synthetics/example_secure_credentials_test.go, pkg/synthetics/secure_credentials.go, pkg/synthetics/synthetics.go
This PR eliminates admin API keys as an authentication method for all resources except Synthetics Secure Credentials, whiich still requires it.
=> feat(synthetics): change resources to use personal api keys

.github/workflows/test.yml, README.md, pkg/logs/example_log_batch_test.go, pkg/logs/example_log_test.go, pkg/logs/logs_integration_test.go, pkg/plugins/plugins_integration_test.go, pkg/plugins/plugins_test.go
- suppress integration tests for fork-based runs
- fix log example test so that it is not run
- add unit tag to plugins unit tests
- refactor logs code for clarity
- update documentation for running integration tests
=> chore: fix integration tests and suppress when run from a fork

pkg/alerts/muting_rules.go
Related to newrelic/terraform-provider-newrelic#954.
`omitempty` causes `fill_option` values of `false` to be omitted from the payload when making requests.
=> fix(alerts): don't omitempty for muting rule's enabled field

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, internal/http/graphql.go, pkg/infrastructure/infrastructure.go, pkg/synthetics/synthetics.go
Without this change, a downstream error returned by GraphQL of
INTERNAL_SERVER_ERROR is not included in the reasons to retry an call.  Here we
rename the IsTimeout method to IsRetryableError to be a bit more generic, and
include another condition in which we might want to retry the call.
=> fix(http): include INTERNAL_SERVER_ERROR as a retry reason

pkg/cloud/cloud_api_integration_test.go
Without this change, our testing account is unlinked from AWS, meaning that our
TF tests start failing due to some s3 bucket access.  Here we seek to avoid
leaving the account in an unlinked state at the end of the tests.
=> tests(cloud): avoid unlinking our account as the final step

CHANGELOG.md, internal/version/version.go
- **entities:** Generate Getter helpers for EntityInterfaces
- **entities:** change the get functions to not be on ptrs
=> chore(changelog): Update CHANGELOG for v0.54.0

README.md, pkg/dashboards/dashboards_api_integration_test.go, pkg/dashboards/types.go, pkg/testhelpers/config.go
NON GENERATED CHANGES
Need to make all fields in `DashboardWidgetConfigurationInput` nullable, otherwise we can only create `markdown` widgets.
This needs to be worked into the code gen, but need this for TF stat.
=> fix(dashboards): DashboardWidgetConfigurationInput needs to be nullable

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, internal/http/graphql.go, pkg/errors/errors.go, pkg/errors/errors_test.go, pkg/infrastructure/infrastructure.go, pkg/nerdgraph/nerdgraph_integration_test.go, pkg/synthetics/synthetics.go, pkg/synthetics/synthetics_test.go
Resolves: #605
Note: We'll need to release the Terraform provider with this update to satisfy the parent ticket referenced in #605
=> fix(http): update error message for 401 status code to account for missing API key AND invalid API key

.tutone.yml, pkg/dashboards/types.go
Mad rush to get a fix out, and there was an easy tutone option...  Revert an unnecessary change, and use tutone config to make the required changes.
=> fix(dashboards): remove manual changes so code generation works again

README.md, pkg/alerts/nrql_conditions_integration_test.go, pkg/apiaccess/keys_integration_test.go, pkg/cloud/cloud_api_integration_test.go, pkg/cloud/example_cloud_account_test.go, pkg/dashboards/dashboards_api_integration_test.go, pkg/events/events_integration_test.go, pkg/events/example_basic_test.go, pkg/events/example_batch_test.go, pkg/eventstometrics/eventstometrics_integration_test.go, pkg/nerdstorage/nerdstorage_integration_test.go, pkg/testhelpers/helpers.go
TestAccountID (among other values) are hard-coded into tests making it difficult for folks to contribute.  This removes `testhelpers.TestAccountID`, and updates all tests to read `NEW_RELIC_ACCOUNT_ID` (via helper functions)
=> refactor(testhelpers): Remove hard-coded TestAccountID

pkg/testhelpers/config.go
- During a test run, setting the `NEW_RELIC_LOG_LEVEL` does nothing. This resolves that issue
- Some tests can take a bit longer to perform, so increase the HTTP timeout value
=> chore(testhelpers): Ensure logging, increase timeouts

pkg/alerts/muting_rules.go
This removes omitEmpty from all of the fields in the mutingRuleScheduleUpdateInput struct.
These fields will be managed as empty by Terraform even omitted from a terraform config.
Removing the omitEmpty tag allows these fields to be nulled if they were set and then removed from a user's terraform config.
Removing this tag from MutingRuleUpdate input allows the entire schedule object to be nulled out if that block is removed from a terraform config.
=> (chore) remove omitEmpty from MutingRuleScheduleUpdateInput and MutingRuleUpdateInput.Schedule

pkg/apiaccess/types.go, pkg/cloud/types.go, pkg/edge/types.go, pkg/entities/types.go, pkg/nrdb/types.go, templates/typegen/types.go.tmpl
Tests are currently broken as the API returns a null value, or `[]` set for part of the CloudIntegrations config on the test account.  Completely valid test case, though we do not check for it thus the tests fail.
* Update template for typegen
* `make generate`
=> Fix interface unmarshal on empty / null values

pkg/alerts/muting_rules.go
updating alertsMutingRulesQuery to include ids, which are required to use the other CRUD methods related to muting rules
=> feat(alerts): adding id to alertsMutingRulesQuery

pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api_integration_test.go
There are multiple visualizations, plus config options for the `Configuration` versions that are only available in the `rawConfiguration` field, which we do not currently fetch.
This adds the field to the fetch, and a test to ensure that it's returned.
=> fix(dashboards): Return rawConfiguration on get

pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api_integration_test.go
If you delete a dashboard, then try to fetch it by GUID, you'll get a panic.  Let's not do that.
=> fix(dashboards): Prevent nil dereference on GetDashboardEntity

CHANGELOG.md, internal/version/version.go
- **dashboards:** Prevent nil dereference on GetDashboardEntity
=> chore(changelog): Update CHANGELOG for v0.58.2

pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api_integration_test.go
Should of done this the first time, didn't, now have to back track.
Return that we didn't find it as an error.
=> fix(dashboards): return an error.NotFound instead of nil

CHANGELOG.md, internal/version/version.go
- **dashboards:** return an error.NotFound instead of nil
=> chore(changelog): Update CHANGELOG for v0.58.3

pkg/apm/application_instances.go, pkg/apm/applications.go, pkg/apm/applications_metrics.go, pkg/apm/applications_rest.go, pkg/apm/deployments.go, pkg/apm/key_transactions.go, pkg/apm/labels.go
Hello
As discussed [here](https://github.com/newrelic/newrelic-client-go/issues/721), this PR adds a version of all APM methods that accepts a context parameter.
I did not add a version for applicationsREST internal functions because, well, they are internal.
Thanks!
=> Allow passing context to apm methods

.tutone.yml, pkg/installevents/types.go
For the new install-events-service, we want to override `EpochMilliseconds` to `int64` as the serialization in the client is giving us some headache. This should take care of the unsupported type problems we've been seeing when running the `newrelic-cli` with this branch of the client.
=> fix: type for validation duration

.tutone.yml, pkg/dashboards/dashboards_api.go, pkg/dashboards/dashboards_api_integration_test.go, pkg/dashboards/types.go, templates/nerdgraphclient/client.go.tmpl, tools/go.mod, tools/go.sum
When resolving an issue with billboard input, a type was skipped that is needed.  Update the tutone config to generate the old type, and skip the overridden type.  [Reference](https://github.com/newrelic/newrelic-client-go/commit/c84c84690fd363ecf0b7fa6074359ebc9af4c803#diff-c8fb5f06f26ca2ea1554da789ba1914c18e334991add8cbd66482c4568907a17R208)
=> Fix tutone generation

.tutone.yml, pkg/installevents/types.go
In the `newrelic-cli`, we define `InstallID` as string. In the client, we want to override the `ID` type as a string as well (previously an `int`).
=> fix: override ID type as string

scripts/release.sh
For some reason a branch might not have the correct list of tags, so we need to reference the rest of the branches to see what the actual latest and next tags should be.
=> fix(release): use --tag-mode all-branches for version bump

pkg/installevents/types.go
This PR adds the `DETECTED` status type. The `DETECTED` status is applied to an installation recipe when New Relic instrumentation compatibility is detected.
=> feat(install): add DETECTED status to installevents via code gen

internal/http/client.go, internal/http/client_test.go, internal/http/errors.go, internal/http/graphql.go, pkg/alerts/nerdgraph.go, pkg/entities/entity_integration_test.go, pkg/infrastructure/infrastructure.go, pkg/synthetics/synthetics.go
Previously, any error condition coming from NerdGraph caused the request to fail.  This isn't great as field `deprecations` are now being returned as errors, with the result set.  Example Entities query:
```
entities {
relationships {...}
}
```
Result:
```
This field is deprecated! Please use `relatedEntities` instead.
```
This change implements a custom error method for GraphQL Queries (NerdGraph really) that checks to see if it's a deprecation error and continues anyway.  So now there is a case where you get back a valid response body and an error.
*THIS IS LIKELY TO CAUSE SOME DOWNSTREAM ISSUES* but not sure yet... The updated method to check if an error is valid or not is a bit clumsy, and consists of:
```go
resp, err := client.GetEntities(guids)
if e, ok := …
```
=> fix(http): Better handling of Deprecation Errors for NerdGraph requests

pkg/events/events.go, pkg/events/events_integration_test.go
Adding License Key Authorizer for the Event API. To keep backwards compatibility the Insight Insert Key is prioritised over the License Key.
The reason for adding this authorizer is to make it easy in the New Relic CLI to create an event without requiring an Insights Insert key.
=> Add license key authorization for the Event API.

.tutone.yml, pkg/installevents/installevents_api.go, pkg/installevents/installevents_api_integration_test.go, pkg/installevents/types.go
**Note:** The `metadata` field in NerdGraph is an arbitrary key:value object represented as a GraphQL custom scalar type named `InstallationRawMetadata`. Since Tutone translates scalars as strings, we perform an override in our Tutone config to ensure the proper Go type is generated for this field, which is `map[string]interface{}` 😎
=> feat(installevents): implement metadata field as arbitrary key-value store on recipe event 

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
This adds support to the Go Client for sliding window aggregation in NRQL conditions. This feature will be released Feb 1
SlideBy and value functions are mutually exclusive, so i've added slideBy to the baseline NRQL condition integration tests, which also can't have value function set.
This is a prerequisite for https://github.com/newrelic/terraform-provider-newrelic/pull/1552
=> Feat(nrql_conditions): add optional SlideBy field to signal

internal/http/auth.go, internal/http/client_test.go, pkg/contextkeys/contextkeys.go, pkg/contextkeys/contextkeys_test.go, pkg/entities/types.go, pkg/installevents/types.go
Closes https://github.com/newrelic/newrelic-client-go/issues/697
This PR adds an X-Account-ID header on REST requests so the same API key can be used across all account it has access to (not just it's primary account id).
To add the header, users should leverage the request's `context` and add an `X-Account-ID` key in the request's context.  This is done with a `contextkeys` package.
This work is meant to address an issue creating channels for child accounts with New Relic's [terraform-provider-newrelic](https://github.com/newrelic/terraform-provider-newrelic/issues/1645).
=> feat(auth): Add X-Account-ID header if value exists in request context

.github/workflows/generate.yml
This job has a tendency to fail at the moment given the amount and frequency of changes happening in NerdGraph. We can keep the cron job running, but we don't need to have a red **x** on the `main` branch due to this 😉
=> chore(ci): do not run tutone generate on every push to main

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_test.go
This PR will expose EntityGUID on NRQL Alert Conditions. 
These EntityGUIDs will be exposed to consumers of New Relic's Terraform Provider. 
https://newrelic.atlassian.net/browse/AINTER-8515
In addition to the unit test update, I ran this locally to confirm I could see my EntityGUIDs on existing NRQL Conditions 
```
package main
import (
"fmt"
"github.com/newrelic/newrelic-client-go/newrelic"
)
func main() {
client, err := newrelic.New(newrelic.ConfigPersonalAPIKey("YOUR_API_KEY_HERE"))
if err != nil {
fmt.Printf("error initializing client:", err)
}
conditions, err := client.Alerts.ListNrqlConditions(<Your Policy ID Number Here>)
if err != nil {
fmt.Printf("error listing conditions", err)
}
for _, condition := range conditions {
fmt.Println(*condition.EntityGUID)
}
}
```
=> feat: Expose EntityGUID on NRQL Conditions.

pkg/alerts/nrql_conditions.go
Continuing from https://github.com/newrelic/newrelic-client-go/pull/875
This PR will expose EntityGUIDs on Nrql Conditions that are fetched from NerdGraph. I mistakenly forgot to do this in my previous pull request.
=> feat: Expose EntityGUID on NRQL Conditions when using NerdGraph.

pkg/alerts/types.go
Adds support for 3 additional term threshold operators for static NRQL conditions.
See also: https://github.com/newrelic/terraform-provider-newrelic/pull/1797
Please delete options that are not relevant.
Please delete options that are not relevant.
This merely adds 3 values to the `AlertsNRQLConditionTermsOperatorTypes` struct -- testing is in the context of the Terraform provider updates.
=> feat(alerts): Adds 3 term threshold operators for NRQL conditions

pkg/alerts/nrql_conditions.go
Outlier NRQL conditions have reached end of life and are no longer supported. This PR removes references to this NRQL condition type and its fields.
=> chore(alerts): Remove references to nrql outlier condition type (EOL)

pkg/nrdb/nrdb_integration_test.go, pkg/nrdb/nrdb_query.go, pkg/nrdb/types.go
This PR modifies the `QueryHistory` operation to use the  `actor.queryHistory` endpoint instead of the soon-to-be-deprecated `actor.nrqlQueryHistory`.
This PR also re-enables the failing integration test. Running the integration test (targetting only `pkg/nrdb`) shows:
```
$ NEW_RELIC_API_KEY=... gotestsum -f testname --junitfile ./integration.xml --packages "github.com/newrelic/newrelic-client-go/v2/pkg/nrdb"  -- -v -parallel 4 -tags integration -coverprofile ./integration.tmp github.com/newrelic/newrelic-client-go/v2/pkg/nrdb
PASS pkg/nrdb.TestIntegrationNrdbQueryHistoryQuery (0.94s)
PASS pkg/nrdb.TestIntegrationNrdbQuery (0.97s)
coverage: 17.2% of statements
PASS pkg/nrdb
DONE 2 tests in 2.123s
```
=> fix(nrdb): Use actor.queryHistory NerdGraph endpoint

pkg/workflows/types.go, pkg/workflows/types_unit_test.go, pkg/workflows/workflows_integration_test.go
Currently, once add enrichments to a workflow you cannot remove them unless you remove the entire workflow.
The reason for this is that:
- A `nil` value for `enrichments` field is treated as 'please don't change anything'
- `{"enrichments": {}}` is not a valid value according to our GraphQL schema definition
- `{"enrichments": {"nrql": []}}` is impossible to pass because we have `omitempty` on `AiWorkflowsUpdateEnrichmentsInput::NRQL`
This commit removes `omitempty`, allowing client users to remove all enrichments from a workflow if needed
=> fix(workflows): allow to remove enrichments from workflows

pkg/changetracking/changetracking_api_integration_test.go, pkg/entities/tags_integration_test.go, pkg/workflows/types.go, pkg/workflows/workflows_api.go, pkg/workflows/workflows_integration_test.go, pkg/workflows/workflows_unit_test.go
Reverts newrelic/newrelic-client-go#955
**These changes should only be released once notification triggers are available to all users.**
This NR client always requests all GraphQL fields it knows of, but notification triggers field is behind a feature-flag. The customers with this FF disabled would not be able to use workflows API through this client.
We are reverting this PR temporarily until the flag is fully rolled out.
=> Revert "feat(Workflow): Add notification triggers"

pkg/workflows/types.go, pkg/workflows/workflows_integration_test.go
`omitempty` directive used for boolean fields 'false' was not passed to the backend. 
At the same time, the value for these boolean fields on BE is `true`. 
So it was impossible to create a workflow in a disabled state.
This PR contains a test that reproduces the problem as well as a fix.
=> fix(workflows): fix issue that prevents creation of disabled workflows

pkg/alerts/example_policy_test.go, pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go, pkg/alerts/nrql_conditions_test.go
[NR-9749]https://issues.newrelic.com/browse/NR-9749
This pull request removes the "value function" field and its "single_value" / "sum" type from NRQL alert conditions. The value function field for NRQL alert conditions is deprecated. Additionally, the "sum" value function is retired and there are no "sum" conditions in production today. 
When users create or update NRQL alert conditions, the Conditions API will add "value function". This eliminates the need for clients to supply the value function when interacting with NRQL Alert Conditions.
=> feat: Remove value_function from NRQL Alert Conditions

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
[NR-58047](https://issues.newrelic.com/browse/NR-58047)
Adds `evaluationDelay` to NRQL Conditions in the New Relic Go client. 
*Note, this new NerdGraph field is protected by a feature flag. I have added the integration testing account to this feature flag. This `evaluationDelay` field will not be added to RPM. 
Users should be able to create, update, read, and delete NRQL Alert Static and Baseline conditions well which have an evaluation delay.
=> feat: Add evaluation delay to nrql conditions

pkg/changetracking/changetracking_api_integration_test.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
The _omitempty_ directive is preventing the ScriptLanguage field from being passed to the API when set to an empty string.  According to the documentation an empty string must be specified when targeting the legacy (Node 10) runtime.  This is currently preventing synthetic script monitors that target the legacy runtime from being created.
There is a bit more detail provided in issue #982.  
This pull request includes a fix to remove the _omitempty_ directive, two copied and pasted tests to verify, and a missing integration tag on an unrelated integration test.
=> fix(synthetics): resolved error targeting legacy runtimes

internal/http/client.go, internal/http/client_test.go, internal/http/request.go, pkg/config/config.go
This PR enables prepending additional requesting service names to a request header to facilitate tracking additional services that call the client. For example, the CLI we'll be able to know the CLI was called from with our Deployment Marker GitHub Action.
=> feat: facilitate additional service names for NewRelic-Requesting-Services request header via env var

pkg/dashboards/dashboards_types.go
Added Raw Configuration properties to dashboard widget.
1. Legend
2. null values
3. colors
4. units
5. facet
=> fix(one_dashboard): added raw configuration properties to one dashboard resource

build/test.mk, pkg/alerts/muting_rules_integration_test.go, pkg/alerts/policies_integration_test.go, pkg/changetracking/changetracking_api_integration_test.go, pkg/entities/entity_integration_test.go, pkg/entities/tags_integration_test.go, pkg/nerdstorage/nerdstorage_integration_test.go, pkg/servicelevel/service_level_integration_test.go, pkg/testhelpers/helpers.go
These adjustments are needed due to our testing account migration to a v2 account. The PR updates entity GUID references as well as updates the account numbers we reference to our new account number.
=> chore(tests): update entity GUIDs to reference entities in new test account

pkg/apiaccess/keys.go, pkg/apiaccess/keys_integration_test.go, pkg/apiaccess/types.go, pkg/testhelpers/helpers.go
This PR addresses [NR-97066](https://issues.newrelic.com/browse/NR-97066), comprising
- Fixes and refactoring to methods and structures in the `apiaccess` package to fix irregular errors thrown in the event of create/update/delete API Access Keys, addition of formatting to thee errors and test cases to validate the same
- Refactoring the error thrown - `Error: json: cannot unmarshal object into Go struct field .data.apiAccessCreateKeys.errors of type apiaccess.APIAccessKeyErrorInterface` when create/update operations are performed on API Access Keys to fix the issues listed below
Fixes 
- [#1418](https://github.com/newrelic/terraform-provider-newrelic/issues/1418) in the Terraform Provider
- [#2261](https://github.com/newrelic/terraform-provider-newrelic/issues/2261) in the Terraform …
=> fix(apiaccess): fix to the error thrown when API Access Key creation fails

.tutone.yml, pkg/entities/entity.go, pkg/entities/entity_integration_test.go, pkg/entities/entity_test.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
This PR adds the ability to provision a Synthetics scripted browser monitor that can emulate different devices, such as mobile or tablet devices. If a monitor has screenshots enabled, those screenshots should also be based on the device emulation if defined.
=> feat(synthetics): add device emulation functionality

pkg/dashboards/dashboards_types.go
This PR addresses [NR-108075](https://issues.newrelic.com/browse/NR-108075), comprising of the following changes - 
- Addition of the attribute `Zero` to `DashboardWidgetYAxisLeft` to be sent to the API whenever set, for which the API is already programmed to fit the graph to scale if `zero=false` or print the graph in the given range of values if `zero=true`
Linked changes in dependencies
**terraform-provider-newrelic** : [PR](https://github.com/newrelic/terraform-provider-newrelic/pull/2329)
**newrelic-cli** : [PR](https://github.com/newrelic/newrelic-cli/pull/1450)
=> fix(dashboards): addition of the attribute 'Zero' to DashboardWidgetYAxisLeft

pkg/cloud/cloud_api.go, pkg/cloud/cloud_api_integration_test.go, pkg/cloud/cloud_api_unit_test.go, pkg/cloud/types.go
This PR addresses [NR-110266](https://issues.newrelic.com/browse/NR-110266), go-client changes to facilitate the addition of a new Azure integration ```azureMonitor``` to Terraform, and comprises the following - 
- Changes fetched from Tutone to update the schema of queries/mutations linked to ```cloudConfigureIntegration``` and its counterpart to disable cloud integrations
- Addition of unit tests and integration tests to check if the ```azureMonitor``` integration is created/updated/deleted as expected
[Integration Test Results](https://github.com/newrelic/newrelic-client-go/actions/runs/4818569428/jobs/8580721871#step:6:295)
[Unit Test Results](https://github.com/newrelic/newrelic-client-go/actions/runs/4818569428/jobs/8580722034#step:6:233)
**Note**
The integration test added in this …
=> chore(cloud): update to queries, types to support azure monitor integration from TF

pkg/alerts/nrql_conditions.go
This PR attempts to address the issues raised in newrelic/terraform-provider-newrelic#2332 where the runbook_url attribute cannot be unset/deleted on update.  To fix this I have removed the omitempty option from the RunbookURL field on the update struct.
I wasn't able to add an integration test for this change due to a timing issue that still exists for updates based the comments [here](https://github.com/newrelic/newrelic-client-go/blob/main/pkg/alerts/nrql_conditions_integration_test.go#L423) in the existing integration tests.  (I did _try_ to write tests for the updated fields but that resulted in said timing errors.)
Thanks!
=> fix(alerts): Removed omitempty from RunbookURL in NrqlConditionUpdateBase

pkg/ai/types_ai.go, pkg/notifications/destinations_test.go, pkg/notifications/notifications_integration_test.go
Add to AiNotificationsDestinationFilter the Name attribute.
=> fix(notifications): add name to filter

pkg/dashboards/dashboards_widgets_integration_test.go, pkg/dashboards/types.go
- This PR addresses a fix to an issue in the Terraform Provider : https://github.com/newrelic/terraform-provider-newrelic/issues/2376 to enable creating a dashboard with pages comprising no widgets.
- For this, **omitempty** has been removed next to the relevant datatype, and a test has been added to validate this change.
- For a more detailed explanation on the necessity of these changes, please see this Terraform PR: https://github.com/newrelic/terraform-provider-newrelic/pull/2397
=> fix(dashboards): remove omitempty on widgets to allow creating pages with no widgets

.tutone.yml, pkg/apiaccess/keys.go, pkg/apiaccess/types.go, pkg/apiaccess/types_apiaccess.go
Changed EpochSeconds to `nrtime.EpochSeconds`. This appears to be the correct golang time to handle createdAt fields returned in NerdGraph responses
=> chore(apiaccess): Returning createdAt on keysearch

pkg/agentapplications/types.go, pkg/synthetics/synthetics_api.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
Originally, this was motivated by the need to have the `device emulation` option enabled for the `Simple Browser Monitor` synthetics, but the functionality seems already present. We just need to complete it in the TF provider. However, a couple of minor updates are in this PR, including updating the related test with the `device emulation` fields.
=> Update device emulation test for Simple Browser monitor synthetics

.tutone.yml, pkg/synthetics/synthetics_api.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/synthetics_api_unit_test.go, pkg/synthetics/types.go
This PR includes 
- changes fetched by Tutone in the **synthetics** package to enable the query `automatedTestResults` and the mutation `syntheticsStartAutomatedTest` and associated types and details.
- tests covering multiple scenarios of the mutation and the query
The changes made have nearly been integrated with the CLI, and have been tested with multiple combinations to ensure the properties of attributes generated and listed in this PR lead to no unexpected behaviour in requests unmarshaled from YAML/responses parsed.
**Note:**
- Except for the removal of the `omitempty` of two fields `IsBlocking` and `Overrides` generated by Tutone, no other manual changes have been made to the code generated. All other datatype/struct tag overrides are as specified and generated from `tutone.yml`. …
=> chore(synthetics): addition of schema and functions for synthetics automated tests

pkg/entities/entities_api.go
This PR addresses the addition of **tags** to **GenericEntityOutline** in order to make **tags** accessible by Terraform, which is needed to facilitate a change in the Terraform Provider to the data source **newrelic_synthetics_private_location**, in which the key of a private location is to be retrieved from the tags returned.
(note: given that Tutone is running into errors when trying to refetch the `entities` package, this change has been manually added).
unblocks 
https://github.com/newrelic/terraform-provider-newrelic/pull/2446 
https://github.com/newrelic/terraform-provider-newrelic/pull/2453 (same PR but reopened)
=> fix(GenericEntityOutline): addition of tags to attributes returned

pkg/changetracking/changetracking_api_integration_test.go
`customAttributes` is currently feature-flagged. This change skips `changetracking's` `TestChangeTrackingCreateDeployment_Basic` test as it will return as failure (see below) under current setup.
Test error message:
```
Received unexpected error:
Cannot query field "customAttributes" on type "ChangeTrackingDeployment".
```
=> chore(changetracking): Skip feature-flagged custom attributes test

pkg/synthetics/synthetics_api.go, pkg/synthetics/synthetics_api_unit_test.go, pkg/synthetics/types.go
Update to schema in the **synthetics** package based on minor updates to the schema made for the Automated Testing feature.
=> fix(synthetics_automated_testing): update to schema based on NG updates

pkg/alerts/conditions_integration_test.go, pkg/apm/labels_integration_test.go, pkg/synthetics/monitor_locations_integration_test.go, pkg/synthetics/monitors_integration_test.go, pkg/synthetics/secure_credentials_integration_test.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/workflows/workflows_integration_test.go
This PR fixes the failing integration tests.
1. Tests for deprecated APIs that always throw errors are skipped
2. The Workflows API has some changes we needed to make for v2 users and it is now working again
3. Synthetics tests need to be run sequentially else they throw errors
4. Some tests for cloud and entity tags remain flakey and fail intermittently
=> fix: integration tests

pkg/entities/entity_integration_test.go, pkg/synthetics/monitors_integration_test.go, pkg/synthetics/secure_credentials_integration_test.go, pkg/synthetics/synthetics_api_integration_test.go
In multiple tests used in the `synthetics` package which end up creating/updating/deleting Synthetic Monitors, Private Locations and Secure Credentials, the names of resources created are currently not consistent - 
- Very few of them have a string that helps identify that the source of the entity is `newrelic-client-go`.
- A large number of them have no such identifier and simply have a `mock.RandSeq(5)` as the name of the entity.
This makes it difficult to track down redundant Synthetic entities in the account which may have not been deleted successfully owing to test failures or other similar reasons, and which would need to be cleaned up (given, in recent times, a large number of redundant monitors created by the client's test which remained and did not get deleted, led to the limit …
=> chore: make names of synthetics entities created in tests consistent

tools/go.mod, tools/go.sum
sub. #1088 
Fixes Dependabot Alerts
- https://github.com/newrelic/newrelic-client-go/security/dependabot/33
- https://github.com/newrelic/newrelic-client-go/security/dependabot/34
- https://github.com/newrelic/newrelic-client-go/security/dependabot/32
- https://github.com/newrelic/newrelic-client-go/security/dependabot/31
=> chore(deps): bump github.com/docker/docker from 23.0.1+incompatible to 23.0.8+incompatible in /tools

pkg/entities/entity_integration_test.go, pkg/entities/tags_integration_test.go
Fixes to a few integration tests which are currently failing to run because GUIDs of entites they use no longer exist.
More details on changes made may be found in the comments added against each test-case change.
=> chore(tests): fix tests by replacing obsolete entities and GUIDs

pkg/events/events_batch.go, pkg/logs/logs_batch.go
Code is raising a panic due to the logger string not being correctly interpolated.
Error I got:
```
panic: interface conversion: interface {} is int, not string
goroutine 31 [running]:
github.com/newrelic/newrelic-client-go/v2/pkg/logging.createFieldMap(...)
/Users/mwu/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.26.0/pkg/logging/logrus_logger.go:101
github.com/newrelic/newrelic-client-go/v2/pkg/logging.LogrusLogger.Trace({0x140002aee78?}, {0x104fe35d2, 0xc}, {0x1400039a7a0?, 0x1400026de01?, 0x1400026de40?})
/Users/mwu/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.26.0/pkg/logging/logrus_logger.go:92 +0x1d4
github.com/newrelic/newrelic-client-go/v2/pkg/logs.(*Logs).batchWorker(0x1400091b440, {0x1053d1d38, 0x14000926120}, 0x0) …
```
=> Fix logger string interpolation

.tutone.yml, pkg/synthetics/synthetics_api.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
=> feat(synthetics): addition of support for next-gen runtime to step, cert check, broken links monitors

pkg/entities/types.go, pkg/synthetics/monitors.go, pkg/synthetics/types.go
=> feat: synthetic monitors `MUTED` status EOL in newrelic-client-go

tools/go.mod, tools/go.sum
Fixes https://github.com/newrelic/newrelic-client-go/security/dependabot/35
=> chore(deps): bump up protobuf to 1.33.0 to fix dependabot alert 35

pkg/testhelpers/config.go
We were using the `testhelpers` package to setup a `NewTestConfig` and noticed when trying to test the Insights API calls, it was not being mocked. I believe this is not intentional, so this is a quick fix, but please let me know if this is intentional.
Fixes https://github.com/newrelic/newrelic-client-go/issues/1107
=> fix: When using a testserver, ensure the Insights API is mocked

pkg/entities/entities.go, pkg/entities/entity_test.go
This PR adds some exported helper functions to facilitate better entity search functionality in our downstream tools (newrelic-cli, terraform-provider-newrelic, etc).
=> feat(entities): add entity search query helpers

.tutone.yml, pkg/ai/types_ai.go, pkg/notifications/notifications_api.go, pkg/notifications/notifications_integration_test.go, pkg/notifications/types.go
⚠️ Kindly hold on merging this PR until 18 April, 2024.
This PR adds 2 new changes to destinations schema:
- new type of auth to destinations called custom headers
- new field secureUrl. This struct holds a SecureValue, so only the prefix part which is a non-SecureValue will be shown upon querying the API.
Required by https://github.com/newrelic/terraform-provider-newrelic/pull/2635/
=> feat(destinations): add custom header auth and secureUrl to destinations

.github/workflows/compile.yml, .github/workflows/generate.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, build/tools.mk, go.mod, pkg/testhelpers/helpers.go, tools/go.mod
Bumps up the version of Golang used in dependencies and GitHub workflows to `go1.21`
Approach adapted from https://github.com/newrelic/newrelic-cli/pull/1592 https://github.com/newrelic/terraform-provider-newrelic/pull/2557/
Question: Does this PR **also** need changes in `.golangci.yml` as made in https://github.com/newrelic/newrelic-cli/pull/1592? @sanderblue
=> feat(build): upgrade to Go v1.21 ✨

pkg/entities/entity_guid_validator.go, pkg/entities/entity_guid_validator_test.go
This change will ensure that the customer-provided GUID is valid before it is accepted by the CLI, preventing any potential issues or errors that may arise from invalid input
=> fix(entity): Entity guid validation

.tutone.yml, pkg/customeradministration/customeradministration_api.go, pkg/customeradministration/customeradministration_integration_test.go, pkg/customeradministration/types.go
Currently they're not which means they are sent in the query and as a result the query always return 0 items even if they're there.
Note: I only need the first commit in this PR, but still pushed the rest of the tutone update.
=> fix(customeradministration): change auth_domain filter types in the package to use pointers

.tutone.yml, pkg/organization/organization_api.go, pkg/organization/organization_integration_test.go, pkg/organization/organization_test.go, pkg/organization/organization_unit_test.go
Hi!
We need this mutation for the project we're implementing this so adding it as PR.
Thanks!
_____
This change **does not** affect the New Relic Terraform Provider if consumed, since the `organization` package is not yet used there (as on 24 May, 2024).
=> feat(organization): Add organizationUpdateSharedAccount mutation.

newrelic/newrelic.go
JIRA - https://new-relic.atlassian.net/browse/NR-270753
This PR aims to address the below timeout issue for few customers as it appears CLI is performing few [test calls ](https://github.com/newrelic/newrelic-cli/blob/53c2d81b257fe874d86c4a0b97b14489d9e7cd99/internal/install/command.go#L178)to verify if the New Relic endpoints are reachable and this infra-alert.service is being invoked during this specific [call](https://github.com/newrelic/newrelic-client-go/blob/0e073a6f00c54832713063f6e37222759337ff41/pkg/region/region_constants.go#L27).
FATAL Get "https://login.newrelic.com/login?return_to=https%3A%2F%2Finfrastructure-alert.service.newrelic.com%2Fv2": dial tcp 18.188.220.94:443: i/o timeout
=> fix(infra): Discard the infra test api call to prevent timeout issues

.tutone.yml, pkg/customeradministration/customeradministration_integration_test.go, pkg/customeradministration/types.go
Otherwise it gets sent in the query and we get no results even if there are expected results
=> fix(customeradministration): TargetId should be nullable.

pkg/entities/entities_api.go, pkg/entities/types.go
With #1171 merged, the `entities` package was cleaned up and the team has been running tests in the New Relic Terraform Provieder with the latest version comprising #1171 (v2.39.1 of the New Relic Go Client) to make sure nothing's broken and everything's running fine.
A tiny little glitch was found in one of these Terraform integration tests run on https://github.com/newrelic/terraform-provider-newrelic/pull/2708.
Upon further investigation, the cause was found. [This block of code](https://github.com/newrelic/newrelic-client-go/commit/a785453d47562e1bc4747ca36f619f53a9835922#r143811903), which may have been manually added (owing to the issues we faced earlier with the entities package in Tutone) kinda got wiped away by our cleanup PR #1171, though we did change the depth of the `entity` …
=> chore(entities): fix drift with browserapplication properties from entities package

pkg/entities/tags_integration_test.go
This PR has changes related to adding test cases to test reversed key mutations on entity tags. The main purpose of these test cases is to check whether NerdGraph is returning correct error messages or not when a user tries to mutate reserved keys (immutable keys), e.g., "account" and "accountId".
- This PR is part of part of this ticket: https://new-relic.atlassian.net/browse/NR-273648
- The terraform changes are part of this PR: https://github.com/newrelic/terraform-provider-newrelic/pull/2710
=> test(entity_tags): added test cases to test reserved key mutations on entity tags

pkg/dashboards/type_overrides.go
This PR include fix for updating the datatype for "to" and "from" fields in threshold attribute for Table and Line widget in newrelic_one_dashboard.
This is done as a part to fix this [#2703](https://github.com/newrelic/terraform-provider-newrelic/issues/2703) GitHub issue, fixed in PR [#2713](https://github.com/newrelic/terraform-provider-newrelic/issues/2713) in the Terraform Provider's repository.
[Jira Story](https://new-relic.atlassian.net/browse/NR-288587)
=> fix(dashboard): update line and table widget threshold `to` and `from` fields datatype from `int` to `float64`

pkg/dashboards/type_overrides.go
changed the default values for 'to' and 'from' fields in threshold for table and line widget in dashboard.
This PR include update for these field type from float64 to string to omit these fields in nerdgraph request if these fields are not specified in the terraform configuration file.
=> fix: changing the default value for 'to' and 'from' in Table and line widget for newrelic_one_dashboard resource

pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
Added the capability to delete all custom headers for simple/browser synthetic monitors.
changes as of this PR:
- updated the type of []SyntheticsCustomHeaderInput type to pointer.
- relevant changes to support this has been done in terraform provider PR [2725](https://github.com/newrelic/terraform-provider-newrelic/pull/2725)
Jira:  [NR-296277](https://new-relic.atlassian.net/browse/NR-296277)
[NR-296277]: https://new-relic.atlassian.net/browse/NR-296277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(synthetics): alter []SyntheticsCustomHeaderInput to allow empty custom headers in the request

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
https://new-relic.atlassian.net/browse/NR-270141
This PR includes changes to support the usage of a new field with baseline/static NRQL alert conditions, `ignoreOnExpectedTermination`. This field is expected to be live on production soon, in queries and mutations which manage baseline/static NRQL alert conditions (the `expiration` field in these queries and mutations has been updated to contain `ignoreOnExpectedTermination`). Examples of some of these mutations and queries have been depicted below.
https://github.com/newrelic/terraform-provider-newrelic/pull/2700
=> feat(alerts): add support for `ignoreOnExpectedTermination` in `expiration` to NRQL alert conditions

pkg/agentapplications/agentapplications_integration_test.go, pkg/agentapplications/types.go
Currently, if user send the value for `cookiesEnabled` as false for browser agent, that is currently being ignored, and the default value of true is being used. Fixed it by changing the boolean field to a pointer.
=> fix(browseragent): changing cookiesEnabled field to pointer type

pkg/dashboards/dashboards_types.go
Currently, if user send the value for legend_enabled as false while creating dashboards, that is currently being ignored, and the default value of true is being used. Fixed it by changing the boolean field to a pointer.
Fixes https://github.com/newrelic/terraform-provider-newrelic/issues/2736
=> fix(dashboard):  changing legend_enabled/legend field to pointer type

pkg/synthetics/synthetics_api.go, pkg/synthetics/synthetics_api_integration_test.go, pkg/synthetics/types.go
Recently, Synthetics added a new feature for scripted, step, and simple browser monitors to support multiple browsers and devices, allowing users to choose from various options when running monitors. Until now, we only had the option of choosing one device combination. As per customer requests and Synthetics' requirements to support the same multi-browser/devices functionality in Terraform, So, support terraform changes we need changes in client-go as well. So, made below changes to support this.
1: Ran tutone and generated synthetics package, which brought browsers, devices fileds.
2: Added integration test cases to validate browsers, devices fields.
3: Sross checked the changes tutone brought in and tested the changes related to these fields along with integration test cases as well.
=> feat(synthetics): Added support for Synthetics Multi Browser, Multi Devices attributes in few synthetics APIs

newrelic/newrelic.go
Adds the Agent library to the New Relic client so that it can be used.
=> fix: Expose agent library

newrelic/newrelic.go
Initialize the agent library, so that it doesn't cause a segmentation violation when used.
Also properly alphabetizes the NewRelic struct.
=> fix: Init agent library

pkg/dashboards/dashboard.go, pkg/dashboards/dashboards_api.go, pkg/dashboards/dashboards_api_integration_test.go, pkg/dashboards/dashboards_types.go, pkg/dashboards/types.go, pkg/entities/entities_api.go, pkg/entities/types.go
Ticket: https://new-relic.atlassian.net/browse/NR-320971
=> feat(dashboards): Added a new field called `excluded` in dashboard variables' (Testing PR)

.tutone.yml, pkg/cloud/cloud_api.go, pkg/cloud/cloud_api_integration_test.go, pkg/cloud/cloud_api_unit_test.go, pkg/cloud/types.go
Please include a summary of the change and which issue is fixed (if relevant).
earlier newrelic_azure_link_account resource was providing only renaming of the link account feature. This PR include changes which will allow users to update all the fields for the resource.
These changes are done as a part of this[ help request.](https://newrelic.slack.com/archives/CP9Q30JDC/p1725499613506239)
jira ticket: https://new-relic.atlassian.net/browse/NR-323227
Fixes # (issue)
Type of change
Please delete options that are not relevant.
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
Checklist:
Please …
=> fix(azure_link_account): add update capability for all fields in azure cloud link account 

pkg/alerts/muting_rules.go, pkg/alerts/muting_rules_test.go, pkg/alerts/types.go
- The addition of the `action_on_muting_rule_window_ended ` attribute in the `newrelic_alert_muting_rule` Terraform resource aims to enhance the functionality of muting rules within New Relic's alerting system using terraform.
- The attribute `actionOnMutingRuleWindowEnded` is added to MutingRule, MutingRuleCreateInput, and MutingRuleUpdateInput structs.
- Link to GitHub Issue: [https://github.com/newrelic/terraform-provider-newrelic/issues/2774](url)
=> feat(alert_muting_rule): Add `action_on_muting_rule_window_ended` attribute in `newrelic_alert_muting_rule` Terraform Resource

pkg/synthetics/synthetics_api_integration_test.go, pkg/workflows/workflows_integration_test.go
- This pull request addresses several issues in integration tests identified in the integration tests of `newrelic-client-go` repository.
- The following test cases have been updated:
- `TestSyntheticsStepMonitor_GetSteps`
- `TestSyntheticsBrokenLinksMonitor_Basic`
- `TestSyntheticsScriptApiMonitorLegacy_Basic`
- `TestIntegrationCreateWorkflow`
- Added appropriate `runtimeType` and `runtimeTypeVersion` to the synthetics test cases.
- Updated the `expectedUpdateOriginalMessage` attribute in `TestIntegrationCreateWorkflow`.
=> fix(integration-tests): Resolve `newrelic-client-go` failed integration tests

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
- **Adds support for the `prediction` fields on NRQL alert conditions**
- `prediction` field is only available for static NRQL conditions (not baseline/anomaly conditions)
- **Current state of the feature:** released internally and open to limited preview (public preview coming shortly)
=> feat(alerts): Add support for prediction to NRQL alert conditions

pkg/alerts/nrql_conditions.go, pkg/alerts/nrql_conditions_integration_test.go
https://new-relic.atlassian.net/browse/NR-368786
Adds support for Alerts NRQL condition signal seasonality for baseline conditions.
Related TF provider PR: https://github.com/newrelic/terraform-provider-newrelic/pull/2844
=> feat(alerts): add support for nrql condition signal seasonality

pkg/synthetics/types.go
Issue mentioned in the [Jira Ticket](https://new-relic.atlassian.net/browse/NR-382532)
**Fix:-** 
**Changes:**
- Removed `omitempty` from the `ResponseValidationText` field in `SyntheticsSimpleMonitorAdvancedOptionsInput`.
**Context:**
This change resolves an issue where the `validation_string` parameter could not be unset in Terraform. After applying this fix, Terraform will correctly unset the `validation_string` when it is removed from the configuration.
=> fix(synthetics): Remove `omitempty` from `ResponseValidationText` to allow unsetting

pkg/dashboards/types.go
https://new-relic.atlassian.net/browse/NR-436500
problem context:
After the multiple account query was launched, the backend system in New Relic platform got be able to respond the JSON file supporting the multiple account data. Once, however, newrelic-cli makes a Terraform formatted file, its output doesn't contain the information on the part of multiple account (losing or trimmed this kind of information). It resulted in different output of dashboards or sometimes the series of provisioning doesn't work as expected.
As tentative solution for this, the customer needs to manually create the dashboard. This is very laborious to do the flow and can potentially include some kind of human error.
=> feat(dashboard): support multiple account id's when creating dashboards
